apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml

secretGenerator:
  - name: notion-notifier-secret
    envs:
      - .env

images:
  - name: notion-notifier
    newName: notion-notifier
    newTag: latest
